name: hinagata-gulp

url:
  http://hinagata-gulp/

site_name:
  hinagata-gulp

description:
  hinagata-gulp website.

keywords: []

share_text:
  hinagata-gulp share text.

share_hashtags: ''

viewport: 
  - width=device-width
  - initial-scale=1.0
  - maximum-scale=1.0
  - user-scalable=0

favicon_url: ''
webclipicon_url: ''

facebook_app_id: ''

ogp_type: 'website'
ogp_image_url: ''
ogp_image_width: 0
ogp_image_height: 0

twitter_card_owner: ''